baseURL = 'https://zip.pet'
# languageCode = 'en-us'
defaultContentLanguage = 'es'
languageCode = 'es'
title = 'Informática'
theme = 'hugo-bearblog'
author = 'Isaac Bruno Quiroga'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true


[params]
	hideMadeWithLine = true
	favicon = 'favicon.ico'
	dateFormat = '02/01'

[markup.goldmark.renderer]
	unsafe = true

[markup]
	[markup.highlight]
		noClasses = false   # importante, para que use clases CSS en lugar de estilos inline
		lineNos = true

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
