baseURL = 'zip.pet'
languageCode = 'en-us'
title = 'Informática'
theme = 'hugo-bearblog'
author = 'Isaac Bruno Quiroga'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
	hideMadeWithLine = true

[markup.goldmark.renderer]
	unsafe = true

[markup]
	[markup.highlight]
		noClasses = false   # importante, para que use clases CSS en lugar de estilos inline
		lineNos = true
